In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("income.csv")

In [3]:
original_row_count=len(df)

In [4]:
sample_df=df.sample(frac=0.1, random_state=32)
sample_row_count=len(sample_df)

In [5]:
print(df.head())
print(sample_df.head())

   age         workclass  fnlwgt     education  education.num  \
0   40  Self-emp-not-inc  223881   Prof-school             15
1   30           Private  149118       HS-grad              9
2   46           Private  109209  Some-college             10
3   32           Private  229566     Assoc-voc             11
4   54                 ?  148657     Preschool              1

       marital.status      occupation   relationship   race     sex  \
0  Married-civ-spouse  Prof-specialty        Husband  White    Male
1            Divorced    Craft-repair  Not-in-family  White  Female
2  Married-civ-spouse    Adm-clerical        Husband  White    Male
3  Married-civ-spouse   Other-service        Husband  White    Male
4  Married-civ-spouse               ?           Wife  White  Female

   capital.gain  capital.loss  hours.per.week native.country income
0         99999             0              70  United-States   >50K
1             0             0              40  United-States  <=50K
2             0             0              40  United-States   >50K
3             0             0              60  United-States   >50K
4             0             0              40         Mexico  <=50K
       age         workclass  fnlwgt     education  education.num  \
20725   46           Private  155659     Bachelors             13
6724    47           Private  194772     Assoc-voc             11
13044   57  Self-emp-not-inc  174760    Assoc-acdm             12
3966    56           Private  108276     Bachelors             13
9133    40           Private  400061  Some-college             10

              marital.status         occupation   relationship  \
20725     Married-civ-spouse  Machine-op-inspct        Husband
6724      Married-civ-spouse  Machine-op-inspct        Husband
13044  Married-spouse-absent    Farming-fishing      Unmarried
3966                 Widowed      Other-service  Not-in-family
9133      Married-civ-spouse  Machine-op-inspct        Husband

                     race     sex  capital.gain  capital.loss  hours.per.week  \
20725               White    Male             0             0              40
6724                White    Male             0             0              40
13044  Amer-Indian-Eskimo    Male             0             0              40
3966                White  Female             0             0              40
9133                Other    Male             0             0              40

      native.country income
20725        Germany   >50K
6724   United-States   >50K
13044  United-States  <=50K
3966   United-States  <=50K
9133   United-States   >50K

In [6]:
#Print the number of rows in the original and sampled dataframes
print(original_row_count)
print(sample_row_count)

25000
2500

In [7]:
sample1_df=df.iloc[::10,:]
sample_row_count=len(sample_df)

In [8]:
print(df.head())
print(sample_df.head())
print(original_row_count)
print(sample_row_count)

   age         workclass  fnlwgt     education  education.num  \
0   40  Self-emp-not-inc  223881   Prof-school             15
1   30           Private  149118       HS-grad              9
2   46           Private  109209  Some-college             10
3   32           Private  229566     Assoc-voc             11
4   54                 ?  148657     Preschool              1

       marital.status      occupation   relationship   race     sex  \
0  Married-civ-spouse  Prof-specialty        Husband  White    Male
1            Divorced    Craft-repair  Not-in-family  White  Female
2  Married-civ-spouse    Adm-clerical        Husband  White    Male
3  Married-civ-spouse   Other-service        Husband  White    Male
4  Married-civ-spouse               ?           Wife  White  Female

   capital.gain  capital.loss  hours.per.week native.country income
0         99999             0              70  United-States   >50K
1             0             0              40  United-States  <=50K
2             0             0              40  United-States   >50K
3             0             0              60  United-States   >50K
4             0             0              40         Mexico  <=50K
       age         workclass  fnlwgt     education  education.num  \
20725   46           Private  155659     Bachelors             13
6724    47           Private  194772     Assoc-voc             11
13044   57  Self-emp-not-inc  174760    Assoc-acdm             12
3966    56           Private  108276     Bachelors             13
9133    40           Private  400061  Some-college             10

              marital.status         occupation   relationship  \
20725     Married-civ-spouse  Machine-op-inspct        Husband
6724      Married-civ-spouse  Machine-op-inspct        Husband
13044  Married-spouse-absent    Farming-fishing      Unmarried
3966                 Widowed      Other-service  Not-in-family
9133      Married-civ-spouse  Machine-op-inspct        Husband

                     race     sex  capital.gain  capital.loss  hours.per.week  \
20725               White    Male             0             0              40
6724                White    Male             0             0              40
13044  Amer-Indian-Eskimo    Male             0             0              40
3966                White  Female             0             0              40
9133                Other    Male             0             0              40

      native.country income
20725        Germany   >50K
6724   United-States   >50K
13044  United-States  <=50K
3966   United-States  <=50K
9133   United-States   >50K
25000
2500

# Stratified random sampling

In [10]:
total_amer_indian_eskimo = len(df[df['race']=='Amer-Indian-Eskimo'])
total_asian_pac_islander = len(df[df['race']=='Asian-Pac-Islander'])
total_black = len(df[df['race']=='Black'])
total_white = len(df[df['race']=='White'])
total_other = len(df[df['race']=='Other'])

In [14]:
sample_size = int(0.1 * original_row_count)
sample_amer_indian_eskimo = int(0.1 * total_amer_indian_eskimo)
sample_asian_pac_islander = int(0.1 * total_asian_pac_islander)
sample_black = int(0.1 * total_black)
sample_white = int(0.1 * total_white)
sample_other = int(0.1 * total_other)
print(sample_size,sample_amer_indian_eskimo,sample_asian_pac_islander,sample_black,sample_white,sample_other)

2500 25 79 241 2132 20

In [16]:
#Generating proportionate samples
amer_indian_eskimo_sample=df[df['race'] =='Amer-Indian-Eskimo'].sample(n=sample_amer_indian_eskimo,random_state=42)
asian_pac_islander_sample=df[df['race'] =='Asian-Pac-Islander'].sample(n=sample_asian_pac_islander,random_state=42)
black_sample=df[df['race'] =='Black'].sample(n=sample_black,random_state=42)
white_sample=df[df['race'] =='White'].sample(n=sample_white,random_state=42)
other_sample=df[df['race'] =='Other'].sample(n=sample_other,random_state=42)
print(len(amer_indian_eskimo_sample),len(asian_pac_islander_sample),len(black_sample),len(white_sample),len(other_sample))

25 79 241 2132 20

In [17]:
#Combining into one single dataframe
sample_df=pd.concat([amer_indian_eskimo_sample,amer_indian_eskimo_sample,black_sample,white_sample,other_sample])
sample_row_count=len(sample_df)
print(df.head())
print(sample_df.head())

   age         workclass  fnlwgt     education  education.num  \
0   40  Self-emp-not-inc  223881   Prof-school             15
1   30           Private  149118       HS-grad              9
2   46           Private  109209  Some-college             10
3   32           Private  229566     Assoc-voc             11
4   54                 ?  148657     Preschool              1

       marital.status      occupation   relationship   race     sex  \
0  Married-civ-spouse  Prof-specialty        Husband  White    Male
1            Divorced    Craft-repair  Not-in-family  White  Female
2  Married-civ-spouse    Adm-clerical        Husband  White    Male
3  Married-civ-spouse   Other-service        Husband  White    Male
4  Married-civ-spouse               ?           Wife  White  Female

   capital.gain  capital.loss  hours.per.week native.country income
0         99999             0              70  United-States   >50K
1             0             0              40  United-States  <=50K
2             0             0              40  United-States   >50K
3             0             0              60  United-States   >50K
4             0             0              40         Mexico  <=50K
       age         workclass  fnlwgt     education  education.num  \
16716   40         Local-gov   95639       HS-grad              9
795     23       Federal-gov   39603  Some-college             10
11207   19  Self-emp-not-inc   30800          10th              6
17466   47           Private  137354  Some-college             10
11725   29           Private  183061       HS-grad              9

              marital.status    occupation    relationship  \
16716          Never-married  Craft-repair  Other-relative
795            Never-married  Craft-repair       Unmarried
11207  Married-spouse-absent  Adm-clerical       Unmarried
17466     Married-civ-spouse  Craft-repair         Husband
11725     Married-civ-spouse  Craft-repair         Husband

                     race     sex  capital.gain  capital.loss  hours.per.week  \
16716  Amer-Indian-Eskimo    Male             0             0              40
795    Amer-Indian-Eskimo    Male             0             0              40
11207  Amer-Indian-Eskimo  Female             0             0              40
17466  Amer-Indian-Eskimo    Male             0             0              40
11725  Amer-Indian-Eskimo    Male             0             0              48

      native.country income
16716  United-States  <=50K
795    United-States  <=50K
11207  United-States  <=50K
17466  United-States  <=50K
11725  United-States  <=50K

In [18]:
print(original_row_count)
print(sample_row_count)

25000
2443

## Cluster Sampling

In [23]:
df.value_counts('marital.status')

marital.status
Married-civ-spouse       11518
Never-married             8204
Divorced                  3390
Separated                  792
Widowed                    766
Married-spouse-absent      312
Married-AF-spouse           18
Name: count, dtype: int64

In [27]:
marital_status=df['marital.status'].unique()
num_marital_status=len(marital_status)
print(marital_status,num_marital_status)
np.random.seed(42)
selected_marital_status =np.random.choice(marital_status,size=num_marital_status//2)
sample_df_4=df[df['marital.status'].isin(selected_marital_status)]
sample_df_4

['Married-civ-spouse' 'Divorced' 'Widowed' 'Never-married' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse'] 7

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
10,21,Private,57916,HS-grad,9,Never-married,Protective-serv,Own-child,White,Male,0,0,40,United-States,<=50K
12,18,Private,127388,12th,8,Never-married,Other-service,Not-in-family,White,Female,0,0,25,United-States,<=50K
22,53,Private,83434,Bachelors,13,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Female,0,0,21,Japan,>50K
23,21,Private,221480,Some-college,10,Never-married,Tech-support,Own-child,White,Female,0,0,25,Ecuador,<=50K
24,34,Private,734193,Some-college,10,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24992,28,Private,282389,HS-grad,9,Never-married,Transport-moving,Not-in-family,White,Male,0,0,60,United-States,<=50K
24993,19,Private,142219,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
24995,40,Private,130834,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
24996,31,Local-gov,33124,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
24998,23,Private,420973,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K

In [36]:
sample_df_5 = sample_df_4.groupby('marital.status')
sample_df_5=sample_df_5.apply(lambda x:x.sample(frac=0.278, random_state = 42),include_groups=False).reset_index(drop=True)
sample_df_5

,age,workclass,fnlwgt,education,education.num,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,29,Private,95423,HS-grad,9,Transport-moving,Husband,White,Male,0,0,80,United-States,<=50K
1,28,?,169631,Assoc-acdm,12,?,Wife,White,Female,0,0,3,United-States,<=50K
2,29,Federal-gov,116394,Bachelors,13,Prof-specialty,Husband,White,Male,0,0,50,United-States,>50K
3,32,Private,281384,HS-grad,9,Other-service,Other-relative,White,Female,0,0,10,United-States,<=50K
4,19,Federal-gov,30559,HS-grad,9,Sales,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2501,29,Private,212102,HS-grad,9,Other-service,Unmarried,Black,Female,0,0,30,United-States,<=50K
2502,34,Private,62124,HS-grad,9,Other-service,Not-in-family,Black,Male,0,0,40,United-States,<=50K
2503,40,Private,260425,Assoc-acdm,12,Tech-support,Unmarried,White,Female,1471,0,32,United-States,<=50K
2504,47,Private,168262,Masters,14,Exec-managerial,Not-in-family,White,Male,99999,0,50,United-States,>50K
2505,64,Private,114994,Some-college,10,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [37]:
clustered_avg = sample_df_5['education.num'].mean()
clustered_avg

9.863128491620111

In [38]:
clustered_avg_fnlwgt = sample_df_5['fnlwgt'].mean()
clustered_avg_fnlwgt

192495.94812450118